### ISSUE TITLE
I can't download the VGG_ILSVRC_16_layers_fc_reduced.h5 file from the google drive in china

### ISSUE THREAD

**Issue by 121649982** [pierluigiferrari/ssd_keras#123]
Are you so kind enought to send to to my email 121649982@qq.com ,or upload to somewhere that I can get it in China! 
Thank you very much!!!

**Comment by pierluigiferrari** [comment]
I wasn't aware that Google Drive isn't accessible in China. Could you maybe try a VPN? It seems that a fair amount of the people using this implementation are Chinese - I wonder how they are doing it?

What cloud storage services do work reliably in China? I read that Dropbox doesn't work in China either.

I'm only willing to upload the trained weight files to a different service if it's worth the effort, i.e. if (1) the current situation makes this repository unusable for many users and (2) there exists a sustainable solution. Since the Chinese government seems to be generally critical towards cloud storage services, is it likely that they will gradually block all major cloud storage providers?
