### ISSUE TITLE
SSD DataGenerator in parallel and Prediction with different sizes of images

### ISSUE THREAD

**Issue by quangvnai** [pierluigiferrari/ssd_keras#128]
A question that is **specific to this SSD implementation**.

Thank you so much for such a great work, Ferrari. It supports us a lot in the way of understanding SSD. 

A. **SSD DataGenerator**
To the best of my knowledge, in Keras, we can generate batches of data for training and evaluating a model by setting the parameter `workers` is some values > 1 in `fit_generator` and `evaluate_generator` methods of the model. After doing that with the Keras SSD model on my machine, I figured out it even slowers the training process. 

1. I'm wondering whether the implementation of DataGenerator for SSD in `object_detection_2d_data_generator.py` can trigger multiple CPUs working to generate batch during training and evaluating the model? If not, how should we modify the code to make it run in parallel seamlessly?

2. How much time to train a full epoch on PASCAL VOC with SSD512 (The train/val data has 11,530 images containing 27,450 ROI annotated objects of 20 classes.) on average from your experience? The training time on my machine when I set `workers=1` as default using `SSDDataAugmentation` chain as the original paper takes about 1 hour 35 minutes per epoch (the training data size = 11,530 I take all train/val data as train data). My machine configuration: GPU - GeForce GTX 1080 (8GB), 64GB RAM, and CPU E5-2630 (8 cores).

B. **FULLY CONVOLUTIONAL NETWORK**
As I witness, SSD might be considered as a fully connected convolutional network which allows us to pass images with different sizes. It is obvious that we should train the model with a fixed image size to take the advantages of training in batch for GPU computation. 
However, when we want to make a prediction on a new image with arbitrary size, in fact, we don't need to resize the image to feed into the fully CNN model. In Keras implementation, to make this work, we can set the `input_shape = (None, None, 3)` for the input, and build the model like `model = Model(inputs= x, outputs=prediction)`. Then, we load the trained weights for the model without any incompatibility. From this point, we can use the model for making prediction on any images of different sizes.

In Caffe implementation, I see that the SSD model works compatibly with any size of images for prediction. But in Keras, we have to specify`img_size` into the `ssd_300` function to build the model. This is because we need this param for passing into `AnchorBox Layer`. 
Anytime I need to make a prediction with different size of images, I must define a new model and `load_weights` or `set_weights` for it. A **solution** for it is that we can resize it to the fixed size as training. However, it's somehow better if we can make a prediction on the real scale of objects in images without distortion.

**So, is there any way to overcome this problem to reduce the overhead of buiding a model and loading weights for it every time on new image?** If possible, I think it will be robust for prediction phase.

Many thanks for reading this issue.

**Comment by pierluigiferrari** [comment]
A.
1. I haven't spent a lot of time on this, but to the best of my knowledge, the concrete implementation of any given data generator is irrelevant for the multiprocessing implementation in Keras' `fit_generator()` and `evaluate_generator()` methods. The method simply creates multiple parallel instances of the given generator and produces mini batches in parallel this way. There are stability considerations (making sure that the parallel generator objects don't all produce the same data, one way to ensure this would be by inheriting from Keras' `Sequence` class) but from a performance standpoint it should be irrelevant what happens inside the generator. I may be wrong. I have observed the same thing when I tried Keras' multiprocessing: It doesn't speed up the training at all. In case you find out that it does indeed have something to do with the specific data generator in this repository, let me know. It might also be worth mentioning that I did experiment with a parallel implementation of my data generator some time ago by distributing the image loading and data augmentation of different images in a batch to different CPU cores, but this also turned out not to speed up the overall batch generation. The reason is that spinning up a parallel thread on a separate core comes with some significant overhead to provide the child process with all the resources and environment state it needs. For this reason, it is only worth launching a parallel process if the work done during the runtime of that process is sufficiently expensive and outweighs the overhead of spinning up the process. In the case of distributing, say, the generation of 16 images in the batch to 8 cores, it's not worth it, since generating the whole batch sequentially is not much slower than the time needed to create all the parallel processes. It would only be worth it if more work was done during the lifetime of the parallel processes. Note that the parallel processes are terminated once their threads terminate, so for each batch they have to be created again. Maybe the reason why Keras' multiprocessing implementation doesn't speed up the batch generation process is similar, or maybe I'm just using it wrong.
2. Don't know, haven't tried. If that's what you're getting, then that's probably what it is.

B.
Just for the sake of using the right terms, there is no such thing as a "fully connected convolutional network". What you mean is "fully convolutional network".

Yes, it would be possible to use this SSD implementation with varying image sizes with certain modifications. First, notice that the `AnchorBoxes` layer is not an absolutely necessary part of the network. It could be left out. This would be a bit of a quick-and-dirty hack, but it would work. As you correctly mention, this layer type is the only reason why you would have to build a new model for every new image. If you removed the `AnchorBoxes` layers, then you could use the same model instance for images of any size. It would, of course, involve a fair amount of work to remove the `AnchorBoxes` layers. You would still need to produce a new set of anchor boxes for every image in Numpy in order to decode the raw model predictions, but you would save all the overhead of creating an entirely new model every time. You would also not be able to use the `DecodeDetections` layer without the `AnchorBoxes` layers.

A better solution might be to keep the `AnchorBoxes` layers, but have them compute a new anchor boxes tensor for every image. The way the `AnchorBoxes` layers currently work is that they compute the anchor boxes only once at the graph initialization (in NumPy) and every time the layer is called, it simply outputs this pre-computed anchor box tensor. This is efficient, but it requires the images to have constant size. If you translated the layer logic in the `call()` method from NumPy to TensorFlow and made the computation dependent on the actual input image size rather than the fixed height and width values currently used, then everything should work for arbitrary image sizes. This might actually be a good idea, maybe I'll try to implement that when I have some time.

Note one thing though: Even though it is generally possible to make the model work with varying input sizes, the model's performance will only be good within a certain narrow range of image sizes. For example, if you train and predict on images that are all somewhere in the neighborhood of 500 pixels wide and 500 pixels high (with some maybe being 423x540 or 600x512, etc.) then the performance might be alright. If, however, you're trying to use such a model with images of size 1024x2048, for example, the performance will depend strongly on the size of the objects in the images. It's important to understand that the absolute receptive field of any given layer in the network is always constant, so in a very high-resolution image, the same layer will see less of the image than with that a lower-resolution image. The point is that making a model work well on variable-size images is anything but trivial and inherently limited.

Another question is: Do you have a practically relevant use case that makes it worth the effort of modifying and tuning a model to work with varying sizes? In the practical use cases that are relevant for my work, the images usually come from a single source (i.e. the same camera), meaning they all have the same size (or at least the same aspect ratio) anyway.

**Comment by quangvnai** [comment]
@pierluigiferrari Thank you so much for very detailed reply. 
A. Your answer is quite clear in two cases. One is the implementation of `multiprocessing` that "The concrete implementation of any given data generator is irrelevant for the multiprocessing implementation in Keras' `fit_generator()` and `evaluate_generator()` methods." At this point, as you said, multiple instances of DataGenerator will be created and several batches will be generated at the same time. As your notice and my notice as well, the implementation of `DataGenerator` should be inherited from `Sequence` class in Keras. Multiple instances of DataGenerator will be created and maybe the batches from these instances can be the same as `warning` from Keras implementation. But it would be nice even with the same image when we apply random augmentation operations -> we will get a somehow different batch. From my experience, I was training Resnet101 on ImageNet. The speed of training was almost 2 times faster when I set `workers = 4`. Maybe, I will try to modify your DataGenerator being inherited from `Sequence`.

The second implementation of `multiprocessing` is what you also mentioned with your experience some time ago, triggering multiprocessing images in a batch. Actually, I just tried it out yesterday and got what you said. We have a trade-off between the time preprocessing images, and the time of overhead when creating processes and gathering the results. If a batch size is small, say about 8, then the overall time of preprocessing a batch in case of `multiprocessing` would a bit slower. If a batch size is large, say 1024, the overall time of multiprocessing a batch would definitely several times faster. But it would be useless here when a batch size is large because GPU has to wait for a batch to be generated, and a big thing here is for this network the batch size of more than 8 would be over the memory of GPU (8GB) - in case of my modified SSD model (22 million params). 

B. I just edited the term "fully connected convolutional network". In some papers related to object detection, I notice the practice of turning an image into image pyramid (zoom in and out). This is useful in case of low performance for detecting tiny objects or huge objects in the image. I think it is where we need the the network works with scale invariance of images. 

Anw, thank you a lot for your answer. I will close this soon.

**Comment by pierluigiferrari** [comment]
> From my experience, I was training Resnet101 on ImageNet. The speed of training was almost 2 times faster when I set workers = 4. Maybe, I will try to modify your DataGenerator being inherited from Sequence.

That's interesting. So that means that the reason why using more workers doesn't result in a speed-up in this implementation might indeed lie in the design of my generator. In case you find the reason, let me know.

B.
It's not necessary for a pyramid network design to be able to accept variable-size images. The images are simply scaled, and, if necessary, warped, to the respective pyramid resolutions, just like with this detector.

**Comment by quangvnai** [comment]
@pierluigiferrari Thanks for your advice.

**Comment by pierluigiferrari** [comment]
Anytime. I'll close this for now.
