### ISSUE TITLE
Unknown layer: AnchorBoxes

### ISSUE THREAD

**Issue by wastacat** [pierluigiferrari/ssd_keras#18]
Sorry ,I'm s a rookie in keras & Neural network.
Pardom,can I ask you a question?

I complete the model training and save model & weights，but when I want to load model next time ，
there will be mistakes : ValueError: Unknown layer: AnchorBoxes
`
#load model && load weights
model = load_model('./model/ssd7_0.h5')
model.load_weights('./model/ssd7_0_weights.h5')
`
I really want to know how to solve this problem，would like to ask about the experienced elders.
thankes!

**Comment by gloddream** [comment]
is there some way to use load_model('./model/ssd7_0.h5') ?

**Comment by pierluigiferrari** [comment]
there definitely is, i just haven't figured out how yet. i've recently implemented the `get_config()` method in both of the custom layers (L2Normalization and AnchorBoxes), so you should theoretically be able to load the model using

`model = load_model('./model/ssd7_0.h5', custom_objects={'AnchorBoxes': AnchorBoxes, 'L2Normalization': L2Normalization, 'SSDLoss': SSDLoss})`

but for some reason either `model.save` or `load_model` isn't able to use the dictionaries that `get_config()` provides correctly. Since Keras documentation regarding saving and loading models with custom objects is basically non-existent, I didn't bother trying around any longer since I had other stuff to do. If you figure out how to make it work, let me know 🙂

**Comment by pierluigiferrari** [comment]
In case it's still relevant for you guys, using `load_model()` works now.

**Comment by vinay0410** [comment]
Hi @pierluigiferrari ,
According to Official Keras Documentation here, now there is support for saving model's architecture + weights and optimizer state in a single HDF5 file.
So, is it possible to load full model into keras, without passing the ```custom_objects parameters```.
This way any custom trained model can be loaded to run predictions, without knowing custom objects to run predictions.
I did try to save one of you models into a single HDF5 file as mentioned in the documentation, but while loading I get an error ```ValueError: Unknown layer: L2Normalization```.

**Comment by pierluigiferrari** [comment]
@vinay0410 can you point me to that documentation?

**Comment by vinay0410** [comment]
Hi @pierluigiferrari ,
Sorry I forgot to attach the link, I have updated my comment with the link.
[https://keras.io/getting-started/faq/#how-can-i-save-a-keras-model](https://keras.io/getting-started/faq/#how-can-i-save-a-keras-model)

**Comment by pierluigiferrari** [comment]
@vinay0410 I'm afraid you're mixing things up. Saving a model saves its architecture, training configuration, etc., but you still need to provide any custom objects that the model requires when you load it. What you describe above is not possible.

**Comment by sachinkmohan** [comment]
Hi  @pierluigiferrari ! I am so thankful for finding your repository! Great work!! 

I know this issue is resolved. But I was trying to apply quantization(tensorflow model optimisation technique) to your repository and again encountered the AnchorBoxes issue. As an author of this repository, I thought you would be the best person to check the issue with. Any inputs from your end will be of great help.

I have detailed this on tensorflow model optimization issues page. Link [here](https://github.com/tensorflow/model-optimization/issues/620)

**Comment by sachinkmohan** [comment]
> Hi @pierluigiferrari ! I am so thankful for finding your repository! Great work!!
> 
> I know this issue is resolved. But I was trying to apply quantization(tensorflow model optimisation technique) to your repository and again encountered the AnchorBoxes issue. As an author of this repository, I thought you would be the best person to check the issue with. Any inputs from your end will be of great help.
> 
> I have detailed this on tensorflow model optimization issues page. Link [here](https://github.com/tensorflow/model-optimization/issues/620)

The above mentioned problem is now resolved under tensorflow/model-optimization#620. 

All thanks to @Hackerman28 !! :smile:
