### ISSUE TITLE
UnicodeDecodeError: 'rawunicodeescape' codec can't decode bytes in position 80-81: truncated \uXXXX

### ISSUE THREAD

**Issue by rtrahms** [pierluigiferrari/ssd_keras#19]
Hi -
Great example!  I am running through training steps on SSD300 and Pascal VOC data.  Made it through all 10 epochs during the training, saving weights files for every epoch.  On the tenth epoch, a crash occurs (even though it looks like the file was saved).  Is this a bounds issue?  I will be retrying a different number of epochs to see if this only happens on the last epoch.
Thanks,
Rob

UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-4-26ea965e3919> in <module>()
     23 
     24 model_name = 'ssd300_0'
---> 25 model.save('./{}.h5'.format(model_name))
     26 model.save_weights('./{}_weights.h5'.format(model_name))
     27 

~\Anaconda3\envs\tensorflow\lib\site-packages\keras\engine\topology.py in save(self, filepath, overwrite, include_optimizer)
   2554         """
   2555         from ..models import save_model
-> 2556         save_model(self, filepath, overwrite, include_optimizer)
   2557 
   2558     def save_weights(self, filepath, overwrite=True):

~\Anaconda3\envs\tensorflow\lib\site-packages\keras\models.py in save_model(model, filepath, overwrite, include_optimizer)
    105         f.attrs['model_config'] = json.dumps({
    106             'class_name': model.__class__.__name__,
--> 107             'config': model.get_config()
    108         }, default=get_json_type).encode('utf8')
    109 

~\Anaconda3\envs\tensorflow\lib\site-packages\keras\engine\topology.py in get_config(self)
   2327         for layer in self.layers:  # From the earliest layers on.
   2328             layer_class_name = layer.__class__.__name__
-> 2329             layer_config = layer.get_config()
   2330             filtered_inbound_nodes = []
   2331             for original_node_index, node in enumerate(layer.inbound_nodes):

~\Anaconda3\envs\tensorflow\lib\site-packages\keras\layers\core.py in get_config(self)
    658     def get_config(self):
    659         if isinstance(self.function, python_types.LambdaType):
--> 660             function = func_dump(self.function)
    661             function_type = 'lambda'
    662         else:

~\Anaconda3\envs\tensorflow\lib\site-packages\keras\utils\generic_utils.py in func_dump(func)
    173         A tuple `(code, defaults, closure)`.
    174     """
--> 175     code = marshal.dumps(func.__code__).decode('raw_unicode_escape')
    176     defaults = func.__defaults__
    177     if func.__closure__:

UnicodeDecodeError: 'rawunicodeescape' codec can't decode bytes in position 80-81: truncated \uXXXX

**Comment by rtrahms** [comment]
It seems to occur not when the interim weights are stored, but when the model file is stored.  Any clues?

**Comment by pierluigiferrari** [comment]
I see you're on Windows. This is likely an OS-related issue, since I've never experienced this myself when testing the code on both Mac OS Sierra and Ubuntu 16.04 - saving the model works as expected on both platforms.

A quick Google search points to the possible cause that certain Windows versions seem to have trouble encoding forward slash characters. This would indicate that you're facing an issue that is unrelated to Keras or this SSD implementation, but has to do with something else. Here are the discussions I found, let me know if this helps solve this problem:

https://github.com/fchollet/keras/issues/5180
https://stackoverflow.com/questions/41847376/keras-model-to-json-error-rawunicodeescape-codec-cant-decode-bytes-in-posi

In the worst case you could always opt to not save the model at all, but only save the weights and build the model from `keras_ssd300` every time as a work-around.
