### ISSUE TITLE
R port to this fantastic work

### ISSUE THREAD

**Issue by gsimchoni** [pierluigiferrari/ssd_keras#26]
Hi,

Didn't know how to tell you this so I opened an issue: I have translated the SSD7 materials into R using R's Keras wrapper. I of course cited you as the author wherever I could.

This is the repo: https://github.com/gsimchoni/ssdkeras

This is a blog post explaining how I did Snapchat-like face-masks with the SSD7 on faces: http://giorasimchoni.com/2017/12/04/2017-12-04-snap-fu/

Tell me if you'd like to change anything in citations, notice the package is under construction.

Thanks Pierluigi!

**Comment by pierluigiferrari** [comment]
Great work! Thanks for citing me, I'm fine the way it is. I read your blog post, fun stuff 😄.

Two notes:

1. I've recently made some changes that allow loading full models instead of having to build the model each time and then load weights into it. I see your port is based on an earlier commit. In case the ability to load full models is relevant to you, you might want to consider updating.
2. You give suggestions in your article about how to improve the model's performance, and as you mention, SSD7 is a small network whose capacity is quite limited of course. One potentially super-easy way to improve the performance is to just increase the depths of the layers, i.e. increasing the number of filters in each layer. I don't know how much it would help, but it might be worth a shot.
