### ISSUE TITLE
Prediction and ground truth boxes bound whole image?

### ISSUE THREAD

**Issue by shbhas** [pierluigiferrari/ssd_keras#33]
Hi,
I am new to image classification. I tried out the train_ssd300 code exactly the way you implemented it (same VOC datasets, parameters), the only difference is that I had to use decode_y instead of decode_y2 because the latter output an empty matrix each time. When I run the code for 10epochs I get the image with both ground truth and prediction boxes bounding the whole images. Am I missing something? In addition the prediction is completely off and has a low percent. I thought that it was because I didn't train the model enough, but it won't train longer than 7 epochs. Any help would be great!

**Comment by pierluigiferrari** [comment]
10 epochs is not remotely enough. The reason why `decode_y2()` with the default parameters is giving you and empty prediction list is because there simply aren't any good predictions yet. As mentioned in the README, you need to train for at least 20,000 steps (something in that ballpark) until the model starts to make any half-decent predictions. Try to relax the early stopping parameters so the model doesn't stop training so quickly.

**Comment by shbhas** [comment]
Thanks for the quick response!I am training it now and I think it should solve the box issue
