### ISSUE TITLE
 AttributeError: module 'keras.backend' has no attribute 'image_dim_ordering'`

### ISSUE THREAD

**Issue by breakcards** [pierluigiferrari/ssd_keras#338]
Hello,
I am using following versions:
keras : 2.3.1
tf : 1.14.0
I am still not able to deal with the following error
--------------------------------------------------------------------
`45
46 def init(self, gamma_init=20, **kwargs):
---> 47 if (K.set_image_data_format('channels_first')== 'tf'):
48 self.axis = 3
49 else:

AttributeError: module 'keras.backend' has no attribute 'image_dim_ordering'`
-----------------------------------------------------------

**Comment by a-bowers** [comment]
Keras has changed `image_dim_ordering` to `image_data_format`, which it seems you have found based on your copy of line 47, however it seems you're calling the setter for it instead of getting it to compare and still trying it vs 'tf'. I believe the new call for it should be `K.image_data_format() == 'channels_last'`.

This also needs changing in lines 171 and 258 of keras_layers_AnchorBoxes.py, however, after that I am getting a different error of the layers being misshapen:

`ValueError: Layer #25 (named "conv4_3_norm_mbox_conf"), weight <tf.Variable 'conv4_3_norm_mbox_conf/kernel:0' shape=(3, 3, 512, 84) dtype=float32_ref> has shape (3, 3, 512, 84), but the saved weight has shape (324, 512, 3, 3).`

EDIT: fixed above by changing n_classes in the call to ssd_300 to 80 for coco
