### ISSUE TITLE
AttributeError: 'numpy.ndarray' object has no attribute 'pop'

### ISSUE THREAD

**Issue by nealzGu** [pierluigiferrari/ssd_keras#44]
Hi there,

thanks for this repo!

When training, I get this error message:
```
Epoch 1/10
 44/517 [=>............................] - ETA: 8:18 - loss: 43.7727

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-8-fef4cc6cd229> in <module>()
     17                                                          patience=2)],
     18                               validation_data = val_generator,
---> 19                               validation_steps = ceil(n_val_samples/batch_size))
     20 
     21 # TODO: Set the filename (without the .h5 file extension!) under which to save the model and weights.

/usr/local/lib/python2.7/dist-packages/keras/legacy/interfaces.pyc in wrapper(*args, **kwargs)
     85                 warnings.warn('Update your `' + object_name +
     86                               '` call to the Keras 2 API: ' + signature, stacklevel=2)
---> 87             return func(*args, **kwargs)
     88         wrapper._original_function = func
     89         return wrapper

/usr/local/lib/python2.7/dist-packages/keras/engine/training.pyc in fit_generator(self, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
   2113                 batch_index = 0
   2114                 while steps_done < steps_per_epoch:
-> 2115                     generator_output = next(output_generator)
   2116 
   2117                     if not hasattr(generator_output, '__len__'):

/usr/local/lib/python2.7/dist-packages/keras/utils/data_utils.pyc in get(self)
    733             success, value = self.queue.get()
    734             if not success:
--> 735                 six.reraise(value.__class__, value, value.__traceback__)

/usr/local/lib/python2.7/dist-packages/keras/utils/data_utils.pyc in data_generator_task()
    633                 try:
    634                     if self._use_multiprocessing or self.queue.qsize() < max_queue_size:
--> 635                         generator_output = next(self._generator)
    636                         self.queue.put((True, generator_output))
    637                     else:

/home/ubuntu/ssd_keras/ssd_batch_generator.pyc in generate(self, batch_size, shuffle, train, ssd_box_encoder, equalize, brightness, flip, translate, scale, max_crop_and_resize, full_crop_and_resize, random_crop, crop, resize, gray, limit_boxes, include_thresh, subtract_mean, divide_by_stddev, swap_channels, diagnostics)
    962             for j in sorted(batch_items_to_remove, reverse=True):
    963                 batch_X.pop(j)
--> 964                 batch_y.pop(j) # This isn't efficient, but it hopefully should not need to be done often anyway.
    965 
    966             # CAUTION: Converting `batch_X` into an array will result in an empty batch if the images have varying sizes.

AttributeError: 'numpy.ndarray' object has no attribute 'pop'

```
Please, what is the reason for this? 
''pop'' can normally be used for lists, as far as I know, not for ndarrays... is this a bug in the code or something else?
Thanks!

**Comment by pierluigiferrari** [comment]
I'm having trouble reproducing this issue. Yes, `pop()` is a method of lists, not arrays, but `batch_y` **is** a list. In order to reproduce this I've changed the generator to always pop the last batch item, and it works without issues. Are you using one of the Jupyter notebooks to train? Did you make any changes to the code, either in the notebook or elsewhere?

**Comment by nealzGu** [comment]
Hi, strange ...
Here's what I changed in the code:
````in [3]: weights_path = '/home/ubuntu/ssd_keras/pretrained_weights/vgg-16_ssd-fcn_ILSVRC-CLS-LOC.h5'

in [5]: # changed the beginning of the paths to /home/user/ssd_keras/... ````

That's it... 

in ssd_batch_generator.py, Ln 676, the scripts is turning batch_y into an array.

Could I maybe comment-out this whole for-loop and deactivate random cropping?

Thanks!

**Comment by nealzGu** [comment]
Just noticed that random cropping is "False" by default. Why is this happening after all?

**Comment by nealzGu** [comment]
not sure if thats important, but Im also getting this warnings:
````
/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py:509: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  return np.fromstring(tensor.tensor_content, dtype=dtype).reshape(shape)
````

**Comment by pierluigiferrari** [comment]
Well, for starters, this implementation requires Python 3 as stated in the dependencies. I see that you are using Python 2. It makes little sense to try to spot the problem as long as something as basic as the Python version is incorrect. I would also recommend to install things like TensorFlow, Keras, and other libraries within virtual environments (e.g. Anaconda environments) rather than directly so that you can maintain multiple different environment configurations.

As for your comments above:

> in ssd_batch_generator.py, Ln 676, the scripts is turning batch_y into an array.

No, it only turns the i-th item of `batch_y` into an array:

`batch_y[i] = np.array(batch_y[i])`

`batch_y` is still a list.

> Just noticed that random cropping is "False" by default. Why is this happening after all?

Because `max_crop_and_resize` and `full_crop_and_resize` ultimately use `random_crop` to perform the actual cropping.

I wouldn't know why this issue would be related to the Python version (after all, a list is a list regardless of the Python version), but since I cannot reproduce the issue in Python 3, I can only suggest that you use a Python 3 environment.

**Comment by nealzGu** [comment]
ah damnit. didn't see that.

I commented it out and training is running now. will see if the results are still fine, but afterwards I will follow your advice with the virtualenv. Since no one else seems to have this error, this might be the issue. Thanks anyway, will close this now.

**Comment by pierluigiferrari** [comment]
Yeah, commenting it out is actually a good makeshift solution. The only effect will be that some batch items might have no ground truth boxes in them after the random cropping, but this should happen very rarely and likely won't impact the training at all.
