### ISSUE TITLE
Am I using it wrong?

### ISSUE THREAD

**Issue by orlov-alexander** [pierluigiferrari/ssd_keras#5]
Hi!
I'm trying to get into object detection. I've tried to use your SSD7 model on Udacity dataset to detect traffic lights. I've managed to sometimes to spot some traffic lights, but nothing more. It wasn't doing well, so I tried more simple example.

Now I'm trying to use it for one of the simplest tasks - recognizing digits.
I'm generating artificial dataset using [this notebook](https://github.com/orlov-alexander/ssd_text/blob/master/generate_image_and_labels_001.ipynb).
I'm training in [this notebook](https://github.com/orlov-alexander/ssd_text/blob/master/train_text_001.ipynb) using your ssd7 model. But as you can see in the pic in the bottom of the notebook, it is not doing well. I don't understand why it not working at all.

Can you please point me what am I doing wrong?
Thanks, Alexander.

**Comment by pierluigiferrari** [comment]
Hey Alexander, the problem is likely in the scaling factors you chose. You set all scaling factors to 1.0, which is a non-sensical anchor box size for the size of the objects you are trying to detect. All anchor boxes will be as large as the training images themselves. This results in a bad matching process between anchor boxes and ground truth boxes: For any given ground truth box, no anchor box will meet the required IoU similarity with that ground truth box since all anchor boxes are way too large, which leads to the anchor box with the highest IoU similarity to be matched to that ground truth box. Since those IoU similarities with the huge anchor boxes don't have much meaning, the matching process becomes meaningless and a bad target tensor will be created.

Try the following:

Set all scaling factors to a value that leads to anchor boxes whose sizes correspond to the sizes of the objects you are trying to detect. Set the aspect ratios accordingly, too. The sizes and shapes of the anchor boxes should be similar to the sizes and shapes of the objects you are trying to detect. In your case, since all objects you're trying to detect have the same shape and size, try setting all scaling factors and aspect ratios to the same values. Also, it is not immediately clear whether there are any advantages or disadvantages to using multiple predictor layers versus using only one predictor layers if all detectable objects are the same size.

Let me know if this solves the problem.

**Comment by orlov-alexander** [comment]
Thank you for the reply!
I chose these scaling factors because I thought it would be easier to learn. I've used only 1 font and 1 font size, so I basically wanted it to overfit very easy (but I've never seen loss of 0). 

I tried these:

1.)
scales = [0.7, 0.8, 0.9, 1.0, 1.2]
aspect_ratios = [0.5, 1.0, 2.0]

[nothing changed](https://github.com/orlov-alexander/ssd_text/blob/quick_try/train_text_001_different_scales_aspect.ipynb)

2.)
scales = None
aspect_ratios = [1.0]

[threw an error](https://github.com/orlov-alexander/ssd_text/blob/quick_try/train_text_001_no_scale_aspect_ratio_0.ipynb)

Also, aspect_ratios of [1.0, 1.0] throws an error (something with tensor shapes).

So, what's wrong?

**Comment by pierluigiferrari** [comment]
Blind trial and error won't help for setting the scales, you have to compute meaningful values based on your dataset. If your images are 224 by 224 pixels and your ground truth boxes are all 43 (h) by 23 (w) pixels, then your only aspect ratio should be around 0.5 (≈ 23/43) and your only scaling factor should be `h / 224 * sqrt(0.5) ≈ 0.14`. The important point here is that the scaling factors need to represent what fraction of the total image size the detectable objects are. Your ground truth boxes around the digits are only 20% by 10% of the image size, so scaling factors of 0.7 and larger are still way too large. Choosing the scaling factors and (somewhat less importantly, but still importantly) the aspect ratios carefully has strong implications on the matching process.

About the error when passing `scales = None`: I've (hopefully) just fixed this.

**Comment by orlov-alexander** [comment]
Thanks for clarifying!

I fetched updates for your .py files and now it throws a "numpy" error.

> ValueError: Error when checking model target: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 1 array(s), but instead got the following list of 128 arrays.
128 is batch_size.

So, another batch of blind trials and errors:
1. 
scales = None
aspect_ratios = [0.5]
batch_size = 128
[here](https://github.com/orlov-alexander/ssd_text/blob/numpy_array_issue/train_text_001_scales_None_batch_size_128.ipynb)
2. 
scales = None
aspect_ratios = [0.5]
batch_size = 1
[here](https://github.com/orlov-alexander/ssd_text/blob/numpy_array_issue/train_text_001_scales_None_batch_size_1.ipynb)
3.
scales = [0.14, 0.14, 0.14, 0.14, 0.14]
aspect_ratios = [0.5]
batch_size = 128
[here](https://github.com/orlov-alexander/ssd_text/blob/numpy_array_issue/train_text_001_scales_5x0_14_aspect_0_5.ipynb)
4. 
scales = [0.12, 0.13, 0.14, 0.15, 0.16]
aspect_ratios = [0.45, 0.5, 0.55]
batch_size = 128
[here](https://github.com/orlov-alexander/ssd_text/blob/numpy_array_issue/train_text_001_something_wrong_with_dataset_generator.ipynb)

I haven't figured yet why where should be different predictor level, it would take some time.

**Comment by pierluigiferrari** [comment]
I will only get a chance to try to reproduce your error on Monday, but I think I know where the ValueError comes from.

Could you please try the following: In the arguments of `val_dataset.generate()` in the Jupyter notebook, set `train=True`. That should get rid of the error. Please let me know if that works.

Also, another thing: Note that `scales` and `min_scale`/`max_scale` are meant to be used either/or. Whenever you set `scales = None`, then `min_scale` and `max_scale` will be used to compute the scale values. So if you set `scales = None` like in your first two examples, but at the same time you leave `min_scale = 1.0` and `max_scale = 1.0`, then all scaling factors will be 1.0 and you will get the same useless results as in your initial trials. So if you want to set `scales = None`, then you have to set `min_scale` and `max_scale` to some values around 0.14 in order for the model to work as you intend.

**Comment by orlov-alexander** [comment]
Thank you so much!
It is finally working! ;-)
After some trials & erros I figured that I used "centroids" instead of "minmax" when plotting boxes on a picture in the last cell of the jupyter notebook. That's why it was SO messed up ;-)

**Comment by pierluigiferrari** [comment]
You're welcome, I'm glad it's working now!
