### ISSUE TITLE
How to use 'VGG_ILSVRC2016_SSD_300x300_iter_440000.h5'?

### ISSUE THREAD

**Issue by monica352** [pierluigiferrari/ssd_keras#50]
Hi Pierluigi, thank you very much for your pretrained model.

I tried to load 'VGG_VOC0712Plus_SSD_300x300_ft_iter_160000.h5', and this predicted well. But when I loaded 'VGG_ILSVRC2016_SSD_300x300_iter_440000.h5', there were some errors. After I changed the 'n_classes' from 21 to 201, it can be loaded successfully, but there are still errors when I use it for prediction, and I think it is because of the 'classes'.

So did you use all the classes when you trained the model with imagenet? Or you just trained it with 200 classes of them? How should I modify the code if I want to use this pretrained model?

Thank you very much!

**Comment by pierluigiferrari** [comment]
Out of the box, each model can only be used for the number of classes that it was trained on. The shapes of the weights of the classification predictor layers depend on the number of classes (as you can see when you take a look at `keras_ssd300.py`), so if you build a model that is supposed to classify 20 classes and you try to load weights into it that are from a model that classifies 200 classes, you're gonna have a kernel shape mismatch in all the last convolutional layers that are responsible for classification. 

Your options are:

1) Rename the predictor layers and load the weights 'by_name' (which you're doing anyway) so that Keras won't try to load trained weights into the predictor layers. The disadvantage of this is that your predictor layers will then start out learning from scratch.
2) Sub-sample the weights of the predictor layers of the ILSVRC2016 model from 200 classes to whatever the number of classes is that you need. If you need only 20 classes, for example, then you take only one tenth of the original kernels for the classification predictor layers. If your 20 classes are a subset of the 200 ILSVRC classes, then you can slice out just the right parts of the kernel and bias tensors so that you get those parts that responsible for your 20 classes. This is a bit of a pain in the ass, but at the end of the day it's nothing more than a bit of Numpy slicing. You get the weights as Numpy arrays (easy with Keras) and slice out the part of the array you need so that it has the shape you need. Then you put the resulting Numpy arrays back into the model (also easy with Keras). You know the order of the 200 ILSVRC classes and you know how many boxes each predictor layer predicts, so theoretically that is all the information you need to sub-sample the weights optimally. Of course you also sub-sample the weights randomly, or take every tenth kernel, but then the result will be less good.

**Comment by monica352** [comment]
Thank you for your reply!

So it is said that, if I want to fine-tune the pretrained model, I can only load the parts before 'conv4_3_norm_mbox_conf', where something about box are introduced into the net; or I can sub-sample the 200 classes into less classes, and then load the sub-sampled complete weights of the entire network, and then do fine-tune? Is that right?

Thank you very much.

**Comment by pierluigiferrari** [comment]
> So it is said that, if I want to fine-tune the pretrained model, I can only load the parts before the layer of 'conv4_3_norm_mbox_conf', where something about box and 'n_classes' are introduced into the net;

You can load the weights of the `mbox_loc` layers since they don't depend on the number of classes, but you cannot load the weights of the `mbox_conf` layers.

or I can sub-sample the 200 classes into less classes, and then load the sub-sampled complete weights of the entire network, and then do fine-tune? Is that right?

Correct.

**Comment by monica352** [comment]
But the 'mbox_conf' layer starts from 'conv4_3_norm', and it depends on classes, so it is said that models with different classes have different 'conv4_3' layer (because they have different 'conv4_3_norm_mbox_conf'), thus all the weights of layers after conv4_3 will be different as well (because weights of layers after conv4_3 come from conv4_3). If that is the case, does it make sense to only load the 'mbox_loc' part of each layer?

Thank you.

**Comment by pierluigiferrari** [comment]
All layers that use `n_classes` in their first argument (the `filters` argument) depend on the number of classes. All the ones that don't, don't.

It always makes sense to load more pre-trained weights as opposed to fewer trained weights. Any trained weights are always a better starting point for any given layer than randomly initialized weights.

**Comment by monica352** [comment]
OK, thank you very much. I will have a try.
