### ISSUE TITLE
unable to use model.load

### ISSUE THREAD

**Issue by ghost** [pierluigiferrari/ssd_keras#6]
hello,
i want to load model with `model = load_model('./ssd7_0.h5')` (ie. uncomment the line)
i got error after some search, i add
`model = load_model('./ssd7_0.h5', custom_objects={'AnchorBoxes': AnchorBoxes})`
but i got another error
`TypeError: __init__() missing 4 required positional arguments: 'img_height', 'img_width', 'this_scale', and 'next_scale'`

i try another way : trying to create model by code and load weights with `model.load_weights('./ssd7_0_weights.h5') ` ... but finish with `ValueError: Dimension 0 in both shapes must be equal, but are 3 and 12 for 'Assign_42' (op: 'Assign') with input shapes: [3,3,64,24], [12,64,3,3].`

is load model or weights operational ? or need add some code (get_config in AnchorBoxes, ...)

best regard

**Comment by pierluigiferrari** [comment]
Hey,
loading Keras models that contain custom objects had a few issues when I wrote this port, so I avoided the issue altogether by building the model myself each time and loading weights only instead of loading the entire model. Loading weights only does work in the Jupyter notebooks provided in this repository. I'm not sure where the shape mismatch in your case comes from, but be sure that you build the model exactly the same way every time. If you build a model, train it, save the weights, build the model again later, and then load the trained weights into the newly built model, it should work without issues, granted that the model is being built identically both times of course. Looking at your ValueError above I would guess that the weights you are trying to load were trained on a slightly different model than the model you're trying to load them into.
