### ISSUE TITLE
After loading model weights bboxes are not sized right

### ISSUE THREAD

**Issue by lababidi** [pierluigiferrari/ssd_keras#7]
In the image below you can see the green ground truth bbox and the blue inferred bbox my the model. The issue is that this was after the model was loaded back into memory from disk via `load_weights`. If I do inference right after training in a notebook, the bbox is correctly sized from inference. Have you seen anything like this?

**Comment by pierluigiferrari** [comment]
I haven't seen this issue before and can't think of a plausible explanation yet. It's strange that the size of the box is off but the center of the box is still roughly in the right place. I'll spend some more time on this. A few questions:

1. Is this the result after using one of the training notebooks more or less out of the box or did you change a lot of code?
2. Is this behavior consistent, i.e. do you see the same phenomenon on multiple images?

**Comment by lababidi** [comment]
I went ahead and retained and couldn't reproduce it. I must have tweaked a
parameter or one of your layers. I was attempting to get save_model and
load_model writing by tweaking your custom layers. I almost have that
working. Also I found a way to load the VGG weights before training. Are
you interested in that?

**Comment by pierluigiferrari** [comment]
Ah, I'm glad you couldn't reproduce it. And yes, if you have a h5 version of the pretrained VGG weights used in the original Caffe implementation that are compatible with this implementation, that would be great :)

**Comment by lababidi** [comment]
it's approximately 90MB

http://mla.im/r/vgg.h5

**Comment by lababidi** [comment]
just `model.load_weights('vgg.h5)` should work. let me know if it doesn't.

**Comment by pierluigiferrari** [comment]
I managed to load the VGG weights into the SSD300 model, but I had to rename the predictor layers in the model, because otherwise it tried to load weights into the predictor layers but complained that the shapes wouldn't match. It's weird that there seem to be matching layer names for the SSD300 predictor layers in the weights file.

Do you know the origin of these weights? Also, were they trained on classification or localization / object detection? Most trained weights for VGG out there were trained on classification tasks.

**Comment by lababidi** [comment]
I took the VGG weights from keras and exported them as numpy arrays. I
modified your ssd_300 function to load these numpy arrays from file per
layer. I also set the first 3 conv groups to untrainable. I exported this
model's weights and it's what you have.
I'm happy to provide any other help if you need.

**Comment by wushilian** [comment]
Hi,I use keras Apllication model,and it work well.after download keras offered model,you just need model.load_weights('vgg.h5',True)

**Comment by pierluigiferrari** [comment]
Thanks Mahmoud! I ported my own VGG-16 weights since yours don't include the convolutionalized fc6 and fc7 weights. I followed the kernel-subsampling procedure of the original implementation for the fc6 and fc7 weights. I trained SSD300 on Pascal VOC with these weights and it works very well. Download link is in the README if you're interested
