### ISSUE TITLE
How to get the bounding boxes on some unknown objects?

### ISSUE THREAD

**Issue by yanxiangyi** [pierluigiferrari/ssd_keras#75]
Hi @pierluigiferrari ! During the test stage, I wonder if SSD can capture something not only belonging to the training categories. How could I get the bounding boxes not only drawed on the, say dogs but also some unknown objects?

**Comment by pierluigiferrari** [comment]
The short answer is, you can't. The long answer is that you could show any or all of the boxes the model predicts by disabling confidence thresholding and non-maximum suppression, but it would probably be pointless to do so. Since, in a trained model, almost all boxes have confidence of close to zero, you cannot use the confidence criterion to measure whether or not a given box is meaningful. So the only thing you could do is look through all the boxes manually and see if any of them surround objects that you consider meaningful.

**Comment by pierluigiferrari** [comment]
You're welcome!
