### ISSUE TITLE
confusion in coordinates (minmax vs centroids)

### ISSUE THREAD

**Issue by humayun** [pierluigiferrari/ssd_keras#86]
Hi,

I have confusion in coordindates of bounding box when you creating the object and when you creating generator.

In the training the model code, when object of ssd300 class is created, you provide cooridnates as 'centroids' and normalize_coord = True, 
code:
```
model = ssd_300(image_size=(img_height, img_width, 3),
                n_classes=20,
                mode='inference',
                l2_regularization=0.0005,
                scales=[0.1, 0.2, 0.37, 0.54, 0.71, 0.88, 1.05], # The scales for MS COCO are [0.07, 0.15, 0.33, 0.51, 0.69, 0.87, 1.05]
                aspect_ratios_per_layer=[[1.0, 2.0, 0.5],
                                         [1.0, 2.0, 0.5, 3.0, 1.0/3.0],
                                         [1.0, 2.0, 0.5, 3.0, 1.0/3.0],
                                         [1.0, 2.0, 0.5, 3.0, 1.0/3.0],
                                         [1.0, 2.0, 0.5],
                                         [1.0, 2.0, 0.5]],
                two_boxes_for_ar1=True,
                steps=[8, 16, 32, 64, 100, 300],
                offsets=[0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
                limit_boxes=False,
                variances=[0.1, 0.1, 0.2, 0.2],
                coords='centroids',
                normalize_coords=True,
                subtract_mean=[123, 117, 104],
                swap_channels=True,
                confidence_thresh=0.5,
                iou_threshold=0.45,
                top_k=200,
                nms_max_output_size=400)

```
but when you created generator, the format for labels are minmax.
````
# Create a `BatchGenerator` instance and parse the Pascal VOC labels.

dataset = BatchGenerator(box_output_format=['class_id', 'xmin', 'ymin', 'xmax', 'ymax'])

# TODO: Set the paths to the datasets here.

VOC_2007_test_images_dir         = '../../datasets/VOCdevkit/VOC2007/JPEGImages/'
VOC_2007_test_annotations_dir    = '../../datasets/VOCdevkit/VOC2007/Annotations/'
VOC_2007_test_image_set_filename = '../../datasets/VOCdevkit/VOC2007/ImageSets/Main/test.txt'

# The XML parser needs to now what object class names to look for and in which order to map them to integers.
classes = ['background',
           'aeroplane', 'bicycle', 'bird', 'boat',
           'bottle', 'bus', 'car', 'cat',
           'chair', 'cow', 'diningtable', 'dog',
           'horse', 'motorbike', 'person', 'pottedplant',
           'sheep', 'sofa', 'train', 'tvmonitor']

dataset.parse_xml(images_dirs=[VOC_2007_test_images_dir],
                  image_set_filenames=[VOC_2007_test_image_set_filename],
                  annotations_dirs=[VOC_2007_test_annotations_dir],
                  classes=classes,
                  include_classes='all',
                  exclude_truncated=False,
                  exclude_difficult=True,
                  ret=False)

generator = dataset.generate(batch_size=1,
                             shuffle=True,
                             train=False,
                             returns={'processed_images',
                                      'filenames',
                                      'inverse_transform',
                                      'original_images',
                                      'original_labels'},
                             max_crop_and_resize=False,
                             random_pad_and_resize=False,
                             resize=(img_height,img_width))
````

and when you make prediction, you get output also as minmax.

```
# Generate a batch and make predictions.

batch_X, batch_filenames, batch_inverse_coord_transform, batch_original_images, batch_original_labels = next(generator)

i = 0 # Which batch item to look at

print("Image:", batch_filenames[i])
print()
print("Ground truth boxes:\n")
print(np.array(batch_original_labels[i]))

confidence_threshold = 0.5

y_pred = [y_pred[k][y_pred[k,:,1] > confidence_threshold] for k in range(y_pred.shape[0])]

np.set_printoptions(precision=2, suppress=True, linewidth=90)
print("Predicted boxes:\n")
print('    class    conf  xmin    ymin    xmax    ymax')
print(y_pred[0])
```

Can you explain what is happening here when you creating the object and when you making genertor and predicting from model. What is difference if you select everywhere minmax instead of centroids and use normlaize_coord as False, instead of True.

Thanks.

**Comment by pierluigiferrari** [comment]
There is a difference between the coordinate format of the input and output data and the coordinate format that the model uses internally.

The input coordinate format, which is what you set as the `box_output_format` in the `BatchGenerator` constructor, must be the 'corners' format, i.e. `['xmin', 'ymin', 'xmax', 'ymax']`, because the `SSDBoxEncoder` expects the box coordinates to be in this format. Likewise, the model's decoded predictions are always in the 'corners' format. That is, for the input and output data, you have no choice.

Where you can choose the coordinate format is for the model's internal representation of the boxes. That means you can choose whether the model internally learns 'centroids', 'corners', or 'minmax' coordinates. This is what you set in the `coords` parameter. In the decoding stage though, the box coordinates will always be converted to the 'corners' format. The reason to allow different internal coordinate representations was to experiment whether the model can learn some coordinate format better than another. However, in the experiments of the original SSD implementation, the coordinate format didn't seem to make a difference. The original SSD models were trained to learn 'centroids' coordinates and you should always leave `coords = centroids`, because there is no point in setting it otherwise.

The `normalize_coords` parameter simply decides whether or not the box coordinates are being divided by the image height / width. This option has no effect on the training (because the normalization cancels out in the internal box conversion computation) and it is only there because the Caffe implementation provides it.

**Comment by humayun** [comment]
Thanks.

But I still have confusion between corners vs minmax. 

This is what I understand about three different formats. Please correct me if I am wrong.

corners format = (xmin, ymin, width, height) 
minmax format = (xmin, ymin, xmax, ymax)
centroids format = (center_x, center_y, width, height)

For example, I have an image of 300 x 300 pixels with a bounding box in the middle which is starting from x=50, y=50 and size of bounding box is 200 x 200 pixels. The coordinates in three different formats are:

**corners format:**
xmin = 50
ymin = 50
width = 200
height = 200

**minmax format:**
xmin = 50
ymin = 50
xmax = 250
ymax = 250

**centroids format:**
center_x = 150
center_y = 150
width = 200
height = 200

According to you Jupyter Notebook: the input and output format (which is corner):
 
```
print("Predicted boxes:\n")
print('    class    conf  xmin    ymin    xmax    ymax')
print(y_pred_decoded[i])
```
Predicted boxes:
class    conf  xmin    ymin    xmax    ymax
[[  19.      0.63   31.16  273.24   80.15  193.06]]

but actually it should be 

class    conf  xmin    ymin    width height
[[  19.      0.63   31.16  273.24   80.15  193.06]]

because xmax and ymax should always greater than xmin and ymin respectively.

**Comment by pierluigiferrari** [comment]
You have to check out the documentation in the code. As is clearly documented in multiple places, the coordinate formats are defined as follows:

1. 'corners' is (xmin, ymin, xmax, ymax) - the top left and bottom right corners of the box, hence the name.
2. 'minmax' is (xmin, xmax, ymin, ymax) - first the min and max coordinates for x, then the min and max coordinates for y, hence the name.
3. 'centroids' is (center_x, center_y, width, height) - center point of the box plus width and height.
