### ISSUE TITLE
ValueError: cannot reshape array of size 0 into shape (0,newaxis,4)

### ISSUE THREAD

**Issue by tadbeer** [pierluigiferrari/ssd_keras#87]
Error faced:

Epoch 00004: val_loss improved from 217.36631 to 104.59965, saving model to ssd300_weights_epoch-04_loss-137.3789_val_loss-104.5996.h5
Epoch 5/700

 1/13 [=>............................] - ETA: 17:50 - loss: 114.2628
 2/13 [===>..........................] - ETA: 16:58 - loss: 78.6937 
 3/13 [=====>........................] - ETA: 15:14 - loss: 81.4181Traceback (most recent call last):
  File "ssd_training.py", line 243, in <module>
    validation_steps=ceil(n_val_samples / batch_size))
  File "/usr/local/lib/python3.5/dist-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training.py", line 2192, in fit_generator
    generator_output = next(output_generator)
  File "/usr/local/lib/python3.5/dist-packages/keras/utils/data_utils.py", line 793, in get
    six.reraise(value.__class__, value, value.__traceback__)
  File "/usr/local/lib/python3.5/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/keras/utils/data_utils.py", line 658, in _data_generator_task
    generator_output = next(self._generator)
  File "/home/ubuntu/SSD/ssd_batch_generator.py", line 909, in generate
    batch_y_true = ssd_box_encoder.encode_y(batch_y, diagnostics=False) # Encode the labels into the `y_true` tensor that the SSD loss function needs.
  File "/home/ubuntu/SSD/encode_decode_utils.py", line 858, in encode_y
    y_encode_template = self.generate_encode_template(batch_size=len(ground_truth_labels), diagnostics=False)
  File "/home/ubuntu/SSD/encode_decode_utils.py", line 803, in generate_encode_template
    boxes = np.reshape(boxes, (batch_size, -1, 4))
  File "/usr/local/lib/python3.5/dist-packages/numpy/core/fromnumeric.py", line 257, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/usr/local/lib/python3.5/dist-packages/numpy/core/fromnumeric.py", line 52, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: cannot reshape array of size 0 into shape (0,newaxis,4)`

________________________________
During the 5th epoch of training, following error has surfaced. Please explain, that in the last line's error 'reshaping of size 0 into shape (0, newaxis, 4)', how does an array of size zero is being passed to be reshaped. Or any other issue..?

**Comment by pierluigiferrari** [comment]
My first guess would be that this happens because there is no ground truth box left in the entire batch, which is a situation that the `SSDBoxEncoder` doesn't account for. What batch size are you using?

**Comment by tadbeer** [comment]
Thanks, We have a training set of 380 images, val'n set of 34 images, and batch size of 32 was used.

**Comment by pierluigiferrari** [comment]
Is it a possibility that a batch might end up with no ground truth boxes at all?

**Comment by tadbeer** [comment]
Each image in my training data has at-least one ground truth box labelled in PASCAL VOC format. That imo should not result in any batch ending up with zero ground truth box.

**Comment by ManishSoni1908** [comment]
I'm also getting the same error,
Please reply.

**Comment by pierluigiferrari** [comment]
I've updated the data generator, please pull the latest master and try the new version. It's not very likely that this solves your issue, but it might.

In order to narrow down the range of possible causes of the issue, once you pulled the latest master, add print statements to `data_generator/object_detection_2d_data_generator.py`. Add the line

`print("before: ", len(batch_y))`

right before [this code block](https://github.com/pierluigiferrari/ssd_keras/blob/52fef0f67a3b6fc6ae34635161135e45703100cc/data_generator/object_detection_2d_data_generator.py#L718-L729) and the lines

```
print("before: ", len(batch_y))
print()
```
right after it. If the issue keeps occurring, let me know what it prints for the batch where it fails.

**Comment by tadbeer** [comment]
Thanks @pierluigiferrari . The updated master is doing perfect training.
Could you explain what was the issue you fixed in that code update?

**Comment by pierluigiferrari** [comment]
Great! The fix is a side effect of a quite drastic data generator redesign, so it's hard to say what fixed the issue because we never really figured out what exactly caused the issue. One possible reason is that the newly added SSD data augmentation chain (in case you're using that) makes it impossible for an image to end up with no ground truth boxes at all, so an empty batch becomes impossible. Another possible reason is that I cleaned up a few fragile points in the generator code where some edge cases might have been overlooked previously and now they are handled correctly.

I'll close this issue as it appears to be fixed, let me know if anything else comes up.
