### ISSUE TITLE
Support for minmax detection output

### ISSUE THREAD

**Issue by Adnation** [pierluigiferrari/ssd_keras#91]
I am trying to train SSD_300 model on my own data. The data I've is in Pascal VOC format. However in inference mode of model, it throws an error as

`The DetectionOutput layer currently only supports the 'centroids' coordinate format.`

When I debug the code I realised it is not supported yet. But what I clearly didn't understand is how are you doing prediction using Pascal Voc dataset in `ssd300_inference.ipynb`?

Do you have any script that can convert Pascal Voc into centroid data?

**Comment by pierluigiferrari** [comment]
You have to read the documentation in the SSD300 training tutorial properly: 'centroids' is just the coordinate format that the model learns internally, it's not the format of your input data. In order to train an SSD300 on your own dataset, you don't have to change anything in the training tutorial except the paths to your dataset. Everything is preset for training on Pascal VOC-format data already. Also note that in order to train the model, you must build it in 'training' mode, not in 'inference' mode.
