### ISSUE TITLE
help me understand!

### ISSUE THREAD

**Issue by anathema43** [pierluigiferrari/ssd_keras#94]

**Comment by anathema43** [comment]
hello
i wanted to create a project for pedestrian detection but i cant seem to understand how to work on your model if you can guide me as i am a beginner as what should i do after i clone... i know you must be infuriated after reading this but please do help

**Comment by pierluigiferrari** [comment]
If you need help, always make your questions as specific as possible. You're not going to have much luck if you just say "Please help", because nobody will know what exactly you need help with.

As @ilyes495 says, there are a bunch of explanations in the README and in the two training tutorials. If you don't understand what's in there, you probably either need to spend more time on it or you might have more fundamental gaps with regard to Python, Keras, or object detection in general that you need to close before you try to use this SSD implementation.

**Comment by anathema43** [comment]
Thank you ,for your replies. i will try to go through the concepts of obect detection again and then try to ggo through the project explanation.I am new its to deep learning so i am a bit scared of all  big codes i see in this project.. and hopefully next time i cry for help it will be  for a specific portion @pierluigiferrari @ilyes495

**Comment by pierluigiferrari** [comment]
If you need an intro, [here](http://neuralnetworksanddeeplearning.com) is a great intro to a mathematical understanding of deep learning and [here](https://www.youtube.com/playlist?list=PLC1qU-LWwrF64f4QKQT-Vg5Wr4qEE1Zxk) is a good video series about deep learning for computer vision. There are many more sources of course (online courses, etc.), these are just two suggestions.

**Comment by anathema43** [comment]
@pierluigiferrari thanks a lo for guiding me,i  have been learning about deep learning from coursera and also from learn with google ai and after finishing that i will start with your suggested course but i have one quick question for m school project i have to make a face detection and recognition  can it be done using your ssd model ...my plan is to first make a pedestrian detection from your object detection model and then change the program so that it detects only the faces of pedestrian and then use a facial recognition algorithm. and please forgive me if i have made any mistakes in specifications as till date this is my plan.it would be very helpful if you can guide me on how to make this project possible.
